### ISSUE TITLE
Installation from GNU ELPA didn't work

### ISSUE THREAD

**Issue by gvol** [realgud/realgud-lldb#5]
When I installed from GNU ELPA, I only have three files, namely 
- realgud-lldb-autoloads.el 
- realgud-lldb-pkg.el 
- realgud-lldb.el
And then it fails to load because it can't find the relative path of lldb/lldb.  I presume this is just a glitch in the packaging.

**Comment by rocky** [comment]
Yes, this seems to be a packaging problem. As best as I can tell, it is ELPA specific. 

If you go to https://github.com/realgud/realgud-lldb/releases, you will see that the tar (and presumably zip) have the lldb directory. Also if you clone this repository, and build it that way and then run `make dist` you can get a tarball with that directory in there too. Finally this installs from [MELPA](https://melpa.org/#/realgud-lldb)  fine. 

I'll need to contact someone on the ELPA side to figure out how to address. In the meantime, those 3 ways (as well as just cloning or copying files from this repository) is a workaround.

**Comment by rocky** [comment]
With Stefan Monier's help I think this fixed now in version 1.0.2. Double check though since I make mistakes. (That's one reason I work on debuggers).
