### ISSUE TITLE
Using realgud-lldb with NASM assembly source file

### ISSUE THREAD

**Issue by wsgac** [realgud/realgud-lldb#6]
When used with a C source file (compiled with `-g` for debugging symbols), realgud-lldb works perfectly. I can step through the code and my current position is shown in the source buffer.

Now, I've tried the same with NASM assembly language. I have a file which assembles cleanly and runs correctly. I assemble and link it as follows (this is Mac OS X):
`nasm -g -fmacho64 triangle.asm && ld -lSystem -o triangle triangle.o`

I would expect similar behavior, but there is no position tracking within the source file. Is it not supported or are there some additional actions that need to be executed for this to work?

**Comment by rocky** [comment]
This is a bit vague. 

I assume you are able to debug nasm using lldb? 

The way realgud-lldb works is it interprets output from a debugger looking for position information. If the position information is similar to how it wouild look in a C program, then things should work fine. If not, depending on the closeness, it might be handled here, but I'm guessing that a totally new plugin would be needed. 

https://github.com/realgud/realgud-lldb/blob/master/lldb/init.el#L60-L71 has the regular expression that is used for looking for patterns.

**Comment by wsgac** [comment]
I compared the way LLDB behaves in both cases and *yes*, I am able to debug assembled NASM code, but *no*, the position information differs. It becomes apparent immediately after placing a breakpoint. Compare C:
```Breakpoint 1: where = test`main + 22 at test.c:4:7, address = 0x0000000100000f16```
with NASM:
```Breakpoint 1: where = triangle`main, address = 0x0000000100000f6```
And this is the case even after using `clang` to link the assembled binary. I've done some more searching on the net and apparently LLDB on Mac OS X has a hard time getting the correct debugging information. But obviously this is an issue with LLDB, so I'm closing this issue. Thanks.

**Comment by rocky** [comment]
If NASM provides mappig information from address to file, line number, and instruction, it is conceivable that realgud could trigger on the address reported. 

However for this someone would need to be prepared to do some serious Emacs Lisp coding, and that person would not be me. Also, this kind of thing would be done in another repository.
