### ISSUE TITLE
cask-install.el:16:1:Error: Cannot open load file: No such file or directory, ~/.cask/cask.el

### ISSUE THREAD

**Issue by BaoshanPang** [realgud/realgud-lldb#8]
I get this error while trying to install it on Windows, how can I avoid it? Thanks. --Baoshan

**Comment by rocky** [comment]
Can you install other things via cask on Windows? 

If so, maybe you can modify that accordingly for this package.

**Comment by BaoshanPang** [comment]
Thanks for the hint. The issue is gone after cloning cask:
git clone https://github.com/cask/cask ~/.cask

**Comment by dunrix** [comment]
I can't see why this issue is closed. Install still fails with realgud-lldb-20230201 package from MELPA, on Linux too.

It has to be fixed in distributed package instead of manual cloning of `cask` repo pre-install.

Related open issue #9

**Comment by rocky** [comment]
If this isn't OS specific then this would be a duplicate.   At any rate, since this is open-source feel free to put in a PR.
